version: "3"

services:
  mysql80:
    image: mysql:8.0.32
    container_name: mysql_80
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-time-zone=Asia/Seoul
      - --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
