DELIMITER $$

DROP FUNCTION IF EXISTS `FUNC_CONCAT_ID`;
CREATE FUNCTION `FUNC_CONCAT_ID` (
    PARAM1 VARCHAR(35)
, PARAM2 VARCHAR(35)
) RETURNS VARCHAR(35)
BEGIN
	DECLARE RETURN_VALUE VARCHAR(35);

	IF STRCMP(PARAM1, PARAM2) < 0 THEN
		SET RETURN_VALUE = CONCAT(PARAM1, ',', PARAM2);
ELSE
        SET RETURN_VALUE = CONCAT(PARAM2, ',', PARAM1);
END IF;

RETURN RETURN_VALUE;
END $$

DELIMITER ;